/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativetest_HelloWorld */

#ifndef _Included_nativetest_HelloWorld
#define _Included_nativetest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativetest_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativetest_HelloWorld_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
